# Generated by Django 3.2.3 on 2021-06-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0003_emptable_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('May', models.FloatField(default=0)),
                ('June', models.FloatField(default=0)),
                ('July', models.FloatField(default=0)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable')),
            ],
        ),
        migrations.CreateModel(
            name='empAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOne', models.FloatField(default=0)),
                ('dayTwo', models.FloatField(default=0)),
                ('dayThree', models.FloatField(default=0)),
                ('dayFour', models.FloatField(default=0)),
                ('dayFive', models.FloatField(default=0)),
                ('daySix', models.FloatField(default=0)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable')),
            ],
        ),
        migrations.CreateModel(
            name='dailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.CharField(default='null', max_length=20)),
                ('outTime', models.CharField(default='null', max_length=20)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable')),
            ],
        ),
    ]
