# Generated by Django 3.2.3 on 2021-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattendance',
            name='dayEight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='empattendance',
            name='dayNine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='empattendance',
            name='daySeven',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='empattendance',
            name='dayTen',
            field=models.FloatField(default=0),
        ),
    ]
