# Generated by Django 3.2.3 on 2021-06-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_demand',
            name='product_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='export',
            name='product_name',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='Export.client_demand'),
        ),
    ]
