# Generated by Django 3.2.3 on 2021-06-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Export', '0002_auto_20210603_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_demand',
            name='client_country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client_demand',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client_demand',
            name='product_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='export',
            name='product_name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='Export.client_demand'),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
