# Generated by Django 3.2.3 on 2021-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Import', '0004_alter_import_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='order_date',
            field=models.DateField(),
        ),
    ]
