# Generated by Django 3.2.3 on 2021-06-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shopping', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='customers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
    ]
