# Generated by Django 3.2.3 on 2021-06-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20210605_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customers',
            new_name='Customer',
        ),
    ]
