# Generated by Django 3.2.3 on 2021-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_rename_customers_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Customer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='prod_id',
            field=models.TextField(),
        ),
    ]
